use std::env;
use std::path::PathBuf;

fn main() {
    let crate_dir = env::var("CARGO_MANIFEST_DIR").unwrap();
    let output_path = PathBuf::from(&crate_dir)
        .parent()
        .unwrap()
        .join("include")
        .join("dbus_rust.h");

    cbindgen::Builder::new()
        .with_crate(crate_dir)
        .with_language(cbindgen::Language::C)
        .with_include_guard("DBUS_RUST_H")
        .with_namespace("dbus_rust")
        .with_header("/* Generated by cbindgen - DO NOT EDIT */")
        .with_autogen_warning("/* WARNING: this file is generated by cbindgen. Don't modify this manually. */")
        .generate()
        .expect("Unable to generate bindings")
        .write_to_file(output_path);
}