[workspace]
members = [
    "rust-timer",
    "rust-config",
    "commodoro-ffi",
]
resolver = "2"

[workspace.dependencies]
libc = "0.2"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"

[profile.release]
lto = true
opt-level = 3