[package]
name = "commodoro-input-monitor"
version = "0.1.0"
edition = "2021"

[lib]
name = "commodoro_input_monitor"

[dependencies]
libc = { workspace = true }
glib = "0.18"
x11 = { version = "2.21", features = ["xlib", "xss"] }
once_cell = "1.19"

[build-dependencies]
cbindgen = "0.26"