[package]
name = "commodoro-break-overlay"
version = "0.1.0"
edition = "2021"

[lib]
name = "commodoro_break_overlay"

[dependencies]
libc = { workspace = true }
gtk = { version = "0.18", features = ["v3_24"] }
gdk = "0.18"
glib = "0.18"
once_cell = "1.19"

[build-dependencies]
cbindgen = "0.26"
