/* Generated by cbindgen - DO NOT EDIT */

#ifndef BREAK_OVERLAY_RUST_H
#define BREAK_OVERLAY_RUST_H

/* WARNING: this file is generated by cbindgen. Don't modify this manually. */

#include <stdarg.h>
#include <stdbool.h>
#include <stdint.h>
#include <stdlib.h>

typedef struct BreakOverlay BreakOverlay;

typedef struct Option_BreakOverlayCallback Option_BreakOverlayCallback;

struct BreakOverlay *break_overlay_new(void);

void break_overlay_free(struct BreakOverlay *overlay);

void break_overlay_set_callback(struct BreakOverlay *_overlay,
                                struct Option_BreakOverlayCallback callback,
                                void *user_data);

void break_overlay_show(struct BreakOverlay *overlay,
                        const char *break_type,
                        int minutes,
                        int seconds);

void break_overlay_hide(struct BreakOverlay *overlay);

void break_overlay_update_time(struct BreakOverlay *overlay, int minutes, int seconds);

void break_overlay_update_type(struct BreakOverlay *overlay, const char *break_type);

int break_overlay_is_visible(struct BreakOverlay *overlay);

void break_overlay_update_pause_button(struct BreakOverlay *overlay, const char *label);

#endif /* BREAK_OVERLAY_RUST_H */
