#ifndef COMMODORO_CONFIG_H
#define COMMODORO_CONFIG_H

/* This file is auto-generated by cbindgen. Do not edit manually. */

#include <stdarg.h>
#include <stdbool.h>
#include <stdint.h>
#include <stdlib.h>
#include <stdint.h>
#include <stdbool.h>

typedef struct Option_PathBuf Option_PathBuf;

typedef struct Config {
  struct Option_PathBuf config_dir;
  struct Option_PathBuf config_file;
  bool use_persistent;
} Config;

typedef struct Settings {
  int32_t work_duration;
  int32_t short_break_duration;
  int32_t long_break_duration;
  int32_t sessions_until_long_break;
  int auto_start_work_after_break;
  int enable_idle_detection;
  int32_t idle_timeout_minutes;
  int enable_sounds;
  double sound_volume;
  char *sound_type;
  char *work_start_sound;
  char *break_start_sound;
  char *session_complete_sound;
  char *timer_finish_sound;
} Settings;

struct Config *config_new(int use_persistent);

void config_free(struct Config *config);

struct Settings *config_load_settings(struct Config *config);

int config_save_settings(struct Config *config, const struct Settings *settings);

const char *config_get_config_dir(struct Config *config);

struct Settings *settings_new_default(void);

void settings_free(struct Settings *settings);

struct Settings *settings_copy(const struct Settings *settings);

int settings_get_work_duration(const struct Settings *settings);

int settings_get_short_break_duration(const struct Settings *settings);

int settings_get_long_break_duration(const struct Settings *settings);

int settings_get_sessions_until_long_break(const struct Settings *settings);

int settings_get_auto_start_work_after_break(const struct Settings *settings);

int settings_get_enable_idle_detection(const struct Settings *settings);

int settings_get_idle_timeout_minutes(const struct Settings *settings);

int settings_get_enable_sounds(const struct Settings *settings);

double settings_get_sound_volume(const struct Settings *settings);

const char *settings_get_sound_type(const struct Settings *settings);

void settings_set_sound_type(struct Settings *settings, const char *value);

void settings_set_work_start_sound(struct Settings *settings, const char *value);

void settings_set_break_start_sound(struct Settings *settings, const char *value);

void rust_free_string(char *s);

#endif /* COMMODORO_CONFIG_H */
