/* Generated by cbindgen - DO NOT EDIT */

#ifndef COMMODORO_INPUT_MONITOR_H
#define COMMODORO_INPUT_MONITOR_H

/* WARNING: this file is generated by cbindgen. Don't modify this manually. */

#include <stdarg.h>
#include <stdbool.h>
#include <stdint.h>
#include <stdlib.h>

typedef struct Arc_AtomicBool Arc_AtomicBool;

typedef struct InputMonitor {
  AtomicBool is_active;
  AtomicUsize callback;
  AtomicUsize user_data;
  AtomicBool use_global_monitoring;
  Mutex<Option<JoinHandle>> thread_handle;
  struct Arc_AtomicBool stop_flag;
} InputMonitor;

typedef int (*InputMonitorCallback)(void*);

struct InputMonitor *input_monitor_new(void);

void input_monitor_free(struct InputMonitor *monitor);

void input_monitor_set_callback(struct InputMonitor *monitor,
                                InputMonitorCallback callback,
                                void *user_data);

void input_monitor_set_window(struct InputMonitor *monitor, void *_window);

void input_monitor_start(struct InputMonitor *monitor);

void input_monitor_stop(struct InputMonitor *monitor);

int input_monitor_is_active(struct InputMonitor *monitor);

int input_monitor_get_idle_time(struct InputMonitor *_monitor);

#endif /* COMMODORO_INPUT_MONITOR_H */
