/* Generated by cbindgen - DO NOT EDIT */

#ifndef COMMODORO_TRAY_ICON_H
#define COMMODORO_TRAY_ICON_H

/* WARNING: this file is generated by cbindgen. Don't modify this manually. */

#include <stdarg.h>
#include <stdbool.h>
#include <stdint.h>
#include <stdlib.h>

typedef struct TrayIcon {
  void *icon_surface;
  int32_t size;
  TimerState state;
  int32_t remaining_seconds;
  int32_t total_seconds;
  char *tooltip_text;
} TrayIcon;

struct TrayIcon *tray_icon_new(void);

void tray_icon_free(struct TrayIcon *icon);

void tray_icon_update(struct TrayIcon *icon,
                      TimerState state,
                      int remaining_seconds,
                      int total_seconds);

void tray_icon_set_tooltip(struct TrayIcon *icon, const char *tooltip);

int tray_icon_is_embedded(struct TrayIcon *_icon);

void *tray_icon_get_surface(struct TrayIcon *icon);

#endif /* COMMODORO_TRAY_ICON_H */
