#ifndef COMMODORO_AUDIO_H
#define COMMODORO_AUDIO_H

/* This file is auto-generated by cbindgen. Do not edit manually. */

#include <stdarg.h>
#include <stdbool.h>
#include <stdint.h>
#include <stdlib.h>
#include <stdint.h>
#include <stdbool.h>

typedef struct AudioManager {
  double volume;
  AtomicBool enabled;
} AudioManager;

struct AudioManager *audio_manager_new(void);

void audio_manager_free(struct AudioManager *audio);

void audio_manager_play_work_start(struct AudioManager *audio);

void audio_manager_play_break_start(struct AudioManager *audio);

void audio_manager_play_session_complete(struct AudioManager *audio);

void audio_manager_play_long_break_start(struct AudioManager *audio);

void audio_manager_play_timer_finish(struct AudioManager *audio);

void audio_manager_play_idle_pause(struct AudioManager *audio);

void audio_manager_play_idle_resume(struct AudioManager *audio);

void audio_manager_set_volume(struct AudioManager *audio, double volume);

void audio_manager_set_enabled(struct AudioManager *audio, int enabled);

#endif /* COMMODORO_AUDIO_H */
