/* Generated by cbindgen - DO NOT EDIT */

#ifndef DBUS_RUST_H
#define DBUS_RUST_H

/* WARNING: this file is generated by cbindgen. Don't modify this manually. */

#include <stdarg.h>
#include <stdbool.h>
#include <stdint.h>
#include <stdlib.h>

typedef enum DBusCommandResult {
  Success = 0,
  Error = 1,
  NotRunning = 2,
  StartNeeded = 3,
} DBusCommandResult;

/**
 * Parse command string and return the D-Bus method name
 */
const char *dbus_parse_command(const char *str);

/**
 * Send a command via D-Bus to the running Commodoro instance
 */
enum DBusCommandResult dbus_send_command(const char *command, int auto_start, void *_unused);

/**
 * Free a string returned by dbus_parse_command
 */
void dbus_free_string(char *str);

#endif /* DBUS_RUST_H */
