/* Generated by cbindgen - DO NOT EDIT */

#ifndef TRAY_STATUS_ICON_RUST_H
#define TRAY_STATUS_ICON_RUST_H

/* WARNING: this file is generated by cbindgen. Don't modify this manually. */

#include <stdarg.h>
#include <stdbool.h>
#include <stdint.h>
#include <stdlib.h>

typedef struct Option_TrayStatusIconCallback Option_TrayStatusIconCallback;

typedef struct TrayStatusIcon TrayStatusIcon;

struct TrayStatusIcon *tray_status_icon_new(void);

void tray_status_icon_free(struct TrayStatusIcon *tray);

void tray_status_icon_set_callback(struct TrayStatusIcon *_tray,
                                   struct Option_TrayStatusIconCallback callback,
                                   void *user_data);

void tray_status_icon_update(struct TrayStatusIcon *tray,
                             cairo_surface_t *surface,
                             const char *tooltip);

void tray_status_icon_set_visible(struct TrayStatusIcon *tray, int visible);

int tray_status_icon_is_embedded(struct TrayStatusIcon *tray);

#endif /* TRAY_STATUS_ICON_RUST_H */
