[package]
name = "commodoro-timer"
version = "0.1.0"
edition = "2021"

[lib]
name = "commodoro_timer"
crate-type = ["cdylib", "staticlib"]

[dependencies]
libc = { workspace = true }

[build-dependencies]
cbindgen = "0.26"